[tools]
"aqua:starship/starship" = "1.24.2"
"aqua:ajeetdsouza/zoxide" = "0.9.8"
"aqua:sharkdp/fd" = "10.3.0"
"github:cli/cli" = "v2.86.0"
"aqua:BurntSushi/ripgrep" = "15.1.0"
"aqua:ast-grep/ast-grep" = "0.40.5"
"aqua:sxyazi/yazi" = "26.1.4"
"aqua:aristocratos/btop" = "1.4.6"
"aqua:direnv/direnv" = "2.37.1"
"aqua:neovim/neovim" = "0.11.5"
tmux = "3.6a"
"aqua:junegunn/fzf" = "0.67.0"
"aqua:sharkdp/bat" = "0.26.1"
"aqua:eza-community/eza" = "0.23.4"
atuin = "18.11.0"
python = "3.12.12"

[settings]
experimental = true
