[tools]
"aqua:starship/starship" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:cli/cli" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:ast-grep/ast-grep" = "latest"
"aqua:sxyazi/yazi" = "latest"
"aqua:aristocratos/btop" = "latest"
"aqua:direnv/direnv" = "latest"
"aqua:neovim/neovim" = "latest"

[settings]
experimental = true
