add_newline = false
command_timeout = 5000

[character]
error_symbol = "[â¯](bold red)"
success_symbol = "[â¯](bold green)"
vicmd_symbol = "[â®](bold green)"

[cmd_duration]
format = "took [$duration]($style) "
min_time = 500

[directory]
format = " in [$path]($style)[$read_only]($read_only_style) "
truncation_length = 4

[git_status]
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
conflicted = "ğŸ³"
deleted = "ğŸ—‘"
diverged = "ğŸ˜µ"
modified = "ğŸ“"
renamed = "ğŸ‘…"
stashed = "ğŸ“¦"
untracked = "ğŸ¤·"

[hostname]
disabled = false
format = "@[$hostname]($style)"
ssh_only = false
style = "white bold"
trim_at = "."

[time]
disabled = true
time_format = "ğŸ•™ [ %r ]"
use_12hr = false

[username]
disabled = false
format = "[$user]($style)"
show_always = true
style_root = "yellow bold"
style_user = "white bold"
